# Generated by Django 5.2.5 on 2025-08-11 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'permissions': [('schedule_match', 'Can schedule matches')]},
        ),
    ]
