# Generated by Django 5.2.5 on 2025-08-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tactic',
            name='formation',
            field=models.CharField(choices=[('4-4-2', '4-4-2'), ('4-3-3', '4-3-3'), ('3-5-2', '3-5-2'), ('5-3-2', '5-3-2'), ('4-2-3-1', '4-2-3-1'), ('3-4-3', '3-4-3')], max_length=50),
        ),
    ]
