# Generated by Django 5.2.5 on 2025-08-13 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_role'),
        ('tactics', '0002_alter_tactic_formation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tactic',
            name='created_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tactic', to='accounts.profile'),
        ),
    ]
